# Generated by Django 4.2.7 on 2023-12-04 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulk_sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sms', to=settings.AUTH_USER_MODEL),
        ),
    ]
